// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  post_code: { type: myMongoose.Schema.Types.String, required: true },
  city_name: { type: myMongoose.Schema.Types.String, required: true },
  street_name: { type: myMongoose.Schema.Types.String, required: true },

  house_number: { type: myMongoose.Schema.Types.String, required: true },
  accounts_ids: [
    { type: myMongoose.Schema.Types.ObjectId, required: true, ref: "accounts" },
  ],
  bins_ids: [
    { type: myMongoose.Schema.Types.ObjectId, required: true, ref: "bins" },
  ],
  start_activity_date: { type: myMongoose.Schema.Types.Date },
  end_activity_date: { type: myMongoose.Schema.Types.Date },
  is_valide: { type: myMongoose.Schema.Types.Boolean, required: true },

  //   type: { type: myMongoose.Schema.Types.String, required: true },
  //   latitude: { type: myMongoose.Schema.Types.Number, default: null },
  //   longitude: { type: myMongoose.Schema.Types.Number, default: null },
  //   context: { type: myMongoose.Schema.Types.String, default: "" },
  //   label: { type: myMongoose.Schema.Types.String, required: false },
  //   id_gouv: { type: myMongoose.Schema.Types.String, required: false },
  //   city_code: { type: myMongoose.Schema.Types.String, required: true },
};
const schema = new myMongoose.Schema(schemaConfig);

function addressModel(mongoose, Mongoose) {
  return mongoose.model("addresses", schema, "addresses");
}

module.exports = addressModel;
