// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  //   name: { type: myMongoose.Schema.Types.String },
  //   is_actif: { type: myMongoose.Schema.Types.String },
  //   password: { type: myMongoose.Schema.Types.Date },
  //   email: { type: myMongoose.Schema.Types.String },
  //   date_start_activity: { type: myMongoose.Schema.Types.Date },
  //   date_end_activity: { type: myMongoose.Schema.Types.Date },
};
const schema = new myMongoose.Schema(schemaConfig);

function administratorModel(mongoose, Mongoose) {
  return mongoose.model("administrators", schema, "administrators");
}

module.exports = administratorModel;
