// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  articleaccounts_id: {
    type: myMongoose.Schema.Types.ObjectId,
    required: true,
    ref: "articleaccounts",
  },
  comment: { type: myMongoose.Schema.Types.String },
  creation_date: { type: myMongoose.Schema.Types.Date, default: Date() },
};
const schema = new myMongoose.Schema(schemaConfig);

function articleCommentModel(mongoose, Mongoose) {
  return mongoose.model("articlecomments", schema, "articlecomments");
}

module.exports = articleCommentModel;
