// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  hasLike: { type: myMongoose.Schema.Types.Boolean, default: false },
  canRead: { type: myMongoose.Schema.Types.Boolean, default: true },
  articles_id: {
    type: myMongoose.Schema.Types.ObjectId,
    required: true,
    ref: "articles",
  },
  accounts_id: {
    type: myMongoose.Schema.Types.ObjectId,
    required: true,
    ref: "accounts",
  },
};
const schema = new myMongoose.Schema(schemaConfig);

function articleAccountModel(mongoose, Mongoose) {
  return mongoose.model("articleaccounts", schema, "articleaccounts");
}

module.exports = articleAccountModel;
