// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  picture: { type: myMongoose.Schema.Types.String, required: true },
  title: { type: myMongoose.Schema.Types.String },
  body: { type: myMongoose.Schema.Types.String },
  tags: [{ type: myMongoose.Schema.Types.String }],
  creation_date: { type: myMongoose.Schema.Types.Date, default: Date() },
  likes: { type: myMongoose.Schema.Types.Number, default: 0 },
  comments: { type: myMongoose.Schema.Types.Number, default: 0 },
};
const schema = new myMongoose.Schema(schemaConfig);

function articleModel(mongoose, Mongoose) {
  return mongoose.model("articles", schema, "articles");
}

module.exports = articleModel;
