// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  name: { type: myMongoose.Schema.Types.String, required: true },
  bintypes_id: {
    type: myMongoose.Schema.Types.ObjectId,
    required: true,
    ref: "bintypes",
  },
  cycle_number: {
    type: myMongoose.Schema.Types.Number,
    required: true,
    default: 0,
  },
  start_activity_date: { type: myMongoose.Schema.Types.Date },
  end_activity_date: { type: myMongoose.Schema.Types.Date },
  is_active: { type: myMongoose.Schema.Types.Boolean, required: true },
};
const schema = new myMongoose.Schema(schemaConfig);

function binModel(mongoose, Mongoose) {
  return mongoose.model("bins", schema, "bins");
}

module.exports = binModel;
