// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  tokens_id: {
    type: myMongoose.Schema.Types.ObjectId,
    required: true,
    ref: "tokens",
  },
  bins_id: {
    type: myMongoose.Schema.Types.ObjectId,
    required: true,
    ref: "bins",
  },
  weight: {
    type: myMongoose.Schema.Types.Number,
    required: true,
    default: 0,
  },
  deposit_date: {
    type: myMongoose.Schema.Types.Date,
    required: true,
  },
};
const schema = new myMongoose.Schema(schemaConfig);

function binsDepositModel(mongoose, Mongoose) {
  return mongoose.model("binsdeposits", schema, "binsdeposits");
}

module.exports = binsDepositModel;
