// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  type: { type: myMongoose.Schema.Types.String, required: true },
  name: { type: myMongoose.Schema.Types.String, required: true },
};
const schema = new myMongoose.Schema(schemaConfig);

function binTypeModel(mongoose, Mongoose) {
  return mongoose.model("bintypes", schema, "bintypes");
}

module.exports = binTypeModel;
