// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  name: { type: myMongoose.Schema.Types.String },
  departement_code: { type: myMongoose.Schema.Types.String },
  departement_name: { type: myMongoose.Schema.Types.String },
  postal_code: { type: myMongoose.Schema.Types.String },
  creation_date: { type: myMongoose.Schema.Types.Date, default: Date() },
  addresses_ids: [{ type: myMongoose.Schema.Types.ObjectId, ref: "addresses" }],
  // addresses: {
  //   type: myMongoose.Schema.Types.Array,
  //   of: { type: myMongoose.Schema.Types.ObjectId, ref: "addresses" },
  // },
  // administrators: [{ type: myMongoose.Schema.Types.ObjectId }],
  // contact_name: { type: myMongoose.Schema.Types.String },
  // contact_address: {type: myMongoose.Schema.Types.String},
  start_activity_date: { type: myMongoose.Schema.Types.Date },
  end_activity_date: { type: myMongoose.Schema.Types.Date },
  is_active: { type: myMongoose.Schema.Types.Boolean, required: true },
};
const schema = new myMongoose.Schema(schemaConfig);

function municipalityModel(mongoose, Mongoose) {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  // const schema = Mongoose.Schema(schemaConfig, {
  //   timestamps: false,
  // });
  // const schema = mySchema;

  return mongoose.model("municipalities", schema, "municipalities");
}

module.exports = municipalityModel;
