// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const myMongoose = require("mongoose");

const schemaConfig = {
  code: {
    type: myMongoose.Schema.Types.String,
    required: true,
    uppercase: true,
  },
};
const schema = new myMongoose.Schema(schemaConfig);

function tokenModel(mongoose, Mongoose) {
  return mongoose.model("tokens", schema, "tokens");
}

module.exports = tokenModel;
